from abc import ABC, abstractmethod
from typing import Type
from pydantic import BaseModel

class BaseAIClient(ABC):
    """
    Abstract Base Class for AI client integrations.
    Provides standard method for generating validated structured data via Pydantic models.
    """
    @abstractmethod
    def generate_json(
        self, 
        system_prompt: str, 
        user_prompt: str, 
        response_model: Type[BaseModel],
        temperature: float = 0.7
    ) -> BaseModel:
        pass

    @abstractmethod
    def generate_text(
        self, 
        system_prompt: str, 
        user_prompt: str,
        temperature: float = 0.7
    ) -> str:
        """
        Generate raw text content.
        
        Args:
            system_prompt: Context or instructions for the AI behavior.
            user_prompt: The query or instructions for text generation.
            temperature: Sampling temperature.
            
        Returns:
            The raw text string generated by the AI.
        """
        pass
